
jobs:

- job: 'Test'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - bash: |
      echo "Checking for items in keychain..."

      security find-generic-password -l "libtvdb_api_key" -w
      if [[ $? != 0 ]]; then
        echo "Adding api key to keychain..."
        security add-generic-password -a "libtvdb_api_key" -s "libtvdb_api_key" -w "$(LIBTVDB_API_KEY)" -U -T "/usr/bin/security" "~/Library/Keychains/login.keychain"
      fi

      security find-generic-password -l "libtvdb_user_key" -w
      if [[ $? != 0 ]]; then
        echo "Adding user key to keychain..."
        security add-generic-password -a "libtvdb_user_key" -s "libtvdb_user_key" -w "$(LIBTVDB_USER_KEY)" -U -T "/usr/bin/security" "~/Library/Keychains/login.keychain"
      fi

      security find-generic-password -l "libtvdb_user_name" -w
      if [[ $? != 0 ]]; then
        echo "Adding user name to keychain..."
        security add-generic-password -a "libtvdb_user_name" -s "libtvdb_user_name" -w "$(LIBTVDB_USER_NAME)" -U -T "/usr/bin/security" "~/Library/Keychains/login.keychain"
      fi
    displayName: Add Secret to Keychain

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python -m pylint --rcfile=pylintrc libtvdb
    displayName: 'Lint'

  - script: python -m mypy libtvdb/
    displayName: 'Type Check'

  - script: |
      python -m pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
